//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSUKariyer.WEB.UserControls.Cv {
    
    
    public partial class uCvForm {
        
        /// <summary>
        /// uCvFormNavigation1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uCvFormNavigation uCvFormNavigation1;
        
        /// <summary>
        /// uWelcome1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uWelcome uWelcome1;
        
        /// <summary>
        /// uPersonalInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uPersonalInfo uPersonalInfo1;
        
        /// <summary>
        /// uCommunicationInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uCommunicationInfo uCommunicationInfo1;
        
        /// <summary>
        /// uCityCountryInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uCityCountryInfo uCityCountryInfo1;
        
        /// <summary>
        /// uCigaretteUsage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uCigaretteUsage uCigaretteUsage1;
        
        /// <summary>
        /// uUserClubs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uUserClubs uUserClubs1;
        
        /// <summary>
        /// uEducationState1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uEducationState uEducationState1;
        
        /// <summary>
        /// uMasterInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uMasterInfo uMasterInfo1;
        
        /// <summary>
        /// uUniversityInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uUniversityInfo uUniversityInfo1;
        
        /// <summary>
        /// uHighSchoolInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uHighSchoolInfo uHighSchoolInfo1;
        
        /// <summary>
        /// uLanguagelInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uLanguagelInfo uLanguagelInfo1;
        
        /// <summary>
        /// uComputerInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uComputerInfo uComputerInfo1;
        
        /// <summary>
        /// uCertificateInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uCertificateInfo uCertificateInfo1;
        
        /// <summary>
        /// uExamInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uExamInfo uExamInfo1;
        
        /// <summary>
        /// uCourseInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uCourseInfo uCourseInfo1;
        
        /// <summary>
        /// uDrivingLicense1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uDrivingLicense uDrivingLicense1;
        
        /// <summary>
        /// uPositions1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uPositions uPositions1;
        
        /// <summary>
        /// uExperienceInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uExperienceInfo uExperienceInfo1;
        
        /// <summary>
        /// uReferanceInfo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uReferanceInfo uReferanceInfo1;
        
        /// <summary>
        /// uCVState1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uCVState uCVState1;
        
        /// <summary>
        /// uMyPhoto1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uMyPhoto uMyPhoto1;
        
        /// <summary>
        /// uCVResult1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSUKariyer.WEB.UserControls.Cv.Edit.uCVResult uCVResult1;
    }
}
